services:
  api:
    build: .
    container_name: node_api
    ports:
      - '80:80'
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: 'redis:alpine'
    container_name: redis_daniel
    ports:
      - '6379:6379'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
